from langchain_google_genai import ChatGoogleGenerativeAI
from langchain_huggingface import ChatHuggingFace,HuggingFaceEndpoint
from langchain_core.prompts import PromptTemplate, load_prompt
from dotenv import load_dotenv
import streamlit as st

#load key from dotenv file
load_dotenv()

#streamlit ui title
st.title("Movie Script Generator")

#huggingface model setup
def huggingface_model():
    llm = HuggingFaceEndpoint(
        repo_id="deepseek-ai/DeepSeek-R1",
        task="text-generation",
        max_new_tokens=250,
        temperature=1.5,
    )
    model = ChatHuggingFace(llm = llm)
    return model

#Gemini model setup
def gemini_model():
    model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=1.0)
    return model

#streamlit ui components
movie_type = st.selectbox(
    "Select Movie Type",
    ["Action", "Comedy", "Drama", "Horror", "Romance"])
script_length = st.slider("Select Script Length (in line)", 1, 10, 5)
languge = st.selectbox(
    "Select Language",
    ["English", "Bangla", "Spanish", "French", "German"])

model = st.selectbox(
    "Select Model",
    ["gemini-2.5-flash", "deepseek-ai/DeepSeek-R1"])

#load prompt template
template = load_prompt("movie_script_prompt.json")

# #generate  prompt
# prompt = template.invoke({
#     "movie_type": movie_type,
#     "script_length": script_length,
#     "language": languge
# })

#generate script
if st.button("Generate Script"):
    if model == "deepseek-ai/DeepSeek-R1":
        hf_model = huggingface_model()
        chain = template | hf_model
        response = chain.invoke({
            "movie_type": movie_type,
            "script_length": script_length,
            "language": languge
        })
        st.write(f"This Script Generated by {model}")
        st.write(response.content)

    else:
        gemini_model = gemini_model()
        chain = template | gemini_model
        response = chain.invoke({
            "movie_type": movie_type,
            "script_length": script_length,
            "language": languge
        })
        st.write(f"This Script Generated by {model}")
        st.write(response.content)
    



































# user_input = st.text_input("Enter a brief plot idea: ")

# if st.button("Generate Script"):
#     model = ChatGoogleGenerativeAI(model="gemini-2.5-flash", temperature=1.0)
#     result = model.invoke(user_input)
#     st.write(result.content)
#     print(result.content)










# from langchain_huggingface import ChatHuggingFace,HuggingFaceEndpoint
# import streamlit as st
# from dotenv import load_dotenv
# load_dotenv()
# st.title("Movie Script Generator")
# user_input = st.text_input("Enter a brief plot idea: ")
# if st.button("Generate Script"):
#     llm = HuggingFaceEndpoint(
#         repo_id="deepseek-ai/DeepSeek-R1",
#         task="text-generation",
#         max_new_tokens=250,
#         temperature=1.5,
#     )
#     model = ChatHuggingFace(llm = llm)
#     result = model.invoke(user_input)
#     st.write(result.content)
   